[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simsim"
dynamic = ["version"]
authors = [
    {name = "Arild Bergesen Husebø", email="arhusebo@gmail.com"},
]
readme = "README.md"
license = {file = "LICENSE"}